name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: npm run lint

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --no-lockfile
      - run: pnpm run test:ember

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm run test:ember

  try-scenarios:
    name: "ember-try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    timeout-minutes: 7
    needs: test

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - 'ember-lts-3.20'
          - 'ember-lts-3.24'
          - 'ember-release'
          - 'ember-beta'
          - 'ember-canary'
          - 'ember-default-with-jquery'
          - 'ember-classic'
          - 'embroider-safe'
          - 'embroider-optimized'
          - 'no-deprecations'
          - 'ember-release-no-deprecations'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - name: test
        run: pnpm ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
